Update to GCC 15.0.1

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,7 +17,7 @@ jobs:
       id: check-cache
       uses: actions/cache@main
       with:
-        key: gcc-14.2.0
+        key: gcc-15-689
         lookup-only: true
         path: |
           /tmp/x86_64-linux-gnu.tar.xz
@@ -26,6 +26,24 @@ jobs:
       if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
       run: |
         bash './build.sh' 'native'
+    - name: Create logs
+      if: always()
+      run: |
+        declare logs=''
+        
+        while read file; do
+            logs+="${file} "
+        done <<< $(find "/tmp/"*"/build" -wholename '*/config.log')
+        
+        tar --create --file=- ${logs} | xz --threads='0' --compress -9 > '/tmp/logs.tar.xz'
+    - name: Upload logs
+      if: always()
+      uses: actions/upload-artifact@main
+      with:
+        name: logs
+        if-no-files-found: error
+        path: |
+            /tmp/logs.tar.xz
     - name: Generate tarball
       if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
       run: |
@@ -45,7 +63,7 @@ jobs:
       if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
       uses: actions/cache@main
       with:
-        key: gcc-14.2.0
+        key: gcc-15-689
         path: |
           /tmp/x86_64-linux-gnu.tar.xz
           /tmp/x86_64-linux-gnu.tar.xz.sha256
@@ -58,22 +76,17 @@ jobs:
     strategy:
       matrix:
         target: [
-          'ia64-unknown-linux-gnu',
-          'alpha-unknown-linux-gnu',
+          # OpenBSD
+          # 'x86_64-unknown-openbsd',
+          # 'i386-unknown-openbsd',
+          # 'aarch64-unknown-openbsd',
+          # 'arm-unknown-openbsd',
+          
+          # Linux (glibc)
           'x86_64-unknown-linux-gnu',
           'i386-unknown-linux-gnu',
-          'arm-unknown-linux-gnueabi',
           'arm-unknown-linux-gnueabihf',
-          'hppa-unknown-linux-gnu',
-          'aarch64-unknown-linux-gnu',
-          'mips-unknown-linux-gnu',
-          'mipsel-unknown-linux-gnu',
-          'powerpc-unknown-linux-gnu',
-          's390-unknown-linux-gnu',
-          's390x-unknown-linux-gnu',
-          'sparc-unknown-linux-gnu',
-          'powerpc64le-unknown-linux-gnu',
-          'mips64el-unknown-linux-gnuabi64'
+          'aarch64-unknown-linux-gnu'
         ]
     steps:
     - uses: actions/checkout@main
@@ -81,74 +94,15 @@ jobs:
         submodules: true
     - name: Free up some space
       run: |
-        sudo apt purge --allow-remove-essential --auto-remove \
-            '*apache2*' \
-            '*docker*' \
-            '*dotnet*' \
-            '*firefox*' \
-            '*google*' \
-            '*gstreamer*' \
-            '*jdk*' \
-            '*nginx*' \
-            '*php*' \
-            '*ruby*' \
-            '*wayland*' \
-            'auto*' \
-            'azure-cli' \
-            'bind9*' \
-            'clang*' \
-            'container*' \
-            'fonts*' \
-            'gcc-9' \
-            'gcc-10' \
-            'gcc-11' \
-            'gcc-12' \
-            'gh' \
-            'glib*' \
-            'libmono*' \
-            'lld*' \
-            'llvm*' \
-            'mercurial*' \
-            'mysql*' \
-            'postgresql*' \
-            'powershell' \
-            'vim*' \
-            'x11*' \
-            'xdg*' > '/dev/null'
-        sudo apt purge --allow-remove-essential --auto-remove \
-            'linux-*' \
-            'apt' > '/dev/null'
-        sudo rm --recursive --force \
-            "${HOME}/.cargo" \
-            "${HOME}/.rustup" \
-            "${HOME}/linuxbrew" \
-            '/etc/apt' \
-            '/etc/cni/net.d' \
-            '/etc/docker' \
-            '/etc/mono' \
-            '/etc/mysql' \
-            '/lib/tmpfiles.d' \
-            '/opt/'* \
-            '/opt/az' \
-            '/usr/lib/heroku' \
-            '/usr/lib/mono' \
-            '/usr/libexec/docker' \
-            '/usr/local/lib/android' \
-            '/usr/local/lib/android' \
-            '/usr/local/share/man' \
-            '/usr/local/share/vcpkg' \
-            '/usr/share/fonts' \
-            '/usr/share/icons' \
-            '/usr/share/java' \
-            '/usr/share/php' \
-            '/usr/share/swift' \
-            '/var/lib/apache2' \
-            '/var/lib/gems' \
-            '/var/log'
+        curl 'https://raw.githubusercontent.com/AmanoTeam/gha-free-space/refs/heads/master/main.sh' -sSf | bash 
+    - name: Install required dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install build-essential || true
     - name: Restore from cache
       uses: actions/cache@main
       with:
-        key: gcc-14.2.0
+        key: gcc-15-689
         fail-on-cache-miss: true
         path: |
           /tmp/x86_64-linux-gnu.tar.xz
@@ -160,9 +114,102 @@ jobs:
     - name: Build Atar with OBGGCC
       run: |
         source './tools/setup_toolchain.sh'
-        source './submodules/obggcc/tools/setup_toolchain.sh'
+        
+        if [[ '${{ matrix.target }}' == *'-linux-musl'* ]]; then
+            declare -r RAIDEN_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --url 'https://api.github.com/repos/AmanoTeam/Raiden/releases/latest')")"
+            declare -r RAIDEN_TARBALL='/tmp/toolchain.tar.xz'
+            declare -r RAIDEN_URL="https://github.com/AmanoTeam/Raiden/releases/download/${RAIDEN_TAG}/x86_64-unknown-linux-gnu.tar.xz"
+            
+            curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --location --url "${RAIDEN_URL}" --output "${RAIDEN_TARBALL}"
+            tar --directory="$(dirname "${RAIDEN_TARBALL}")" --extract --file="${RAIDEN_TARBALL}"
+            
+            export RAIDEN_HOME='/tmp/raiden'
+            export PATH="${RAIDEN_HOME}/bin:${PATH}"
+            
+            source "${RAIDEN_HOME}/usr/local/share/raiden/autotools/${{ matrix.target }}.sh"
+        elif [[ '${{ matrix.target }}' == *'-linux-gnu'* ]]; then
+            declare -r OBGGCC_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --url 'https://api.github.com/repos/AmanoTeam/obggcc/releases/latest')")"
+            declare -r OBGGCC_TARBALL='/tmp/toolchain.tar.xz'
+            declare -r OBGGCC_URL="https://github.com/AmanoTeam/obggcc/releases/download/${OBGGCC_TAG}/x86_64-unknown-linux-gnu.tar.xz"
+            
+            curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --location --url "${OBGGCC_URL}" --output "${OBGGCC_TARBALL}"
+            tar --directory="$(dirname "${OBGGCC_TARBALL}")" --extract --file="${OBGGCC_TARBALL}"
+            
+            export OBGGCC_HOME='/tmp/obggcc'
+            export PATH="${OBGGCC_HOME}/bin:${PATH}"
+            
+            source "${OBGGCC_HOME}/usr/local/share/obggcc/autotools/${{ matrix.target }}.sh"
+        elif [[ '${{ matrix.target }}' == *'-freebsd' ]]; then
+            declare -r LOKI_TAG="$(jq --raw-output '.tag_name' <<< "$(curl  --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --url 'https://api.github.com/repos/AmanoTeam/Loki/releases/latest')")"
+            declare -r LOKI_TARBALL='/tmp/toolchain.tar.xz'
+            declare -r LOKI_URL="https://github.com/AmanoTeam/Loki/releases/download/${LOKI_TAG}/x86_64-unknown-linux-gnu.tar.xz"
+            
+            curl --silent --connect-timeout '10' --retry '15' --retry-all-errors --fail --location --url "${LOKI_URL}" --output "${LOKI_TARBALL}"
+            tar --directory="$(dirname "${LOKI_TARBALL}")" --extract --file="${LOKI_TARBALL}"
+            
+            export LOKI_HOME='/tmp/loki'
+            export PATH="${LOKI_HOME}/bin:${PATH}"
+            
+            source "${LOKI_HOME}/usr/local/share/loki/autotools/${{ matrix.target }}.sh"
+        elif [[ '${{ matrix.target }}' == *'-netbsd'* ]]; then
+            declare -r DAKINI_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --url 'https://api.github.com/repos/AmanoTeam/Dakini/releases/latest')")"
+            declare -r DAKINI_TARBALL='/tmp/toolchain.tar.xz'
+            declare -r DAKINI_URL="https://github.com/AmanoTeam/Dakini/releases/download/${DAKINI_TAG}/x86_64-unknown-linux-gnu.tar.xz"
+            
+            curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --location --url "${DAKINI_URL}" --output "${DAKINI_TARBALL}"
+            tar --directory="$(dirname "${DAKINI_TARBALL}")" --extract --file="${DAKINI_TARBALL}"
+            
+            export DAKINI_HOME='/tmp/dakini'
+            export PATH="${DAKINI_HOME}/bin:${PATH}"
+            
+            source "${DAKINI_HOME}/usr/local/share/dakini/autotools/${{ matrix.target }}.sh"
+        elif [[ '${{ matrix.target }}' == *'-openbsd' ]]; then
+            # declare -r ATAR_TAG="$(jq --raw-output '.tag_name' <<< "$(curl  --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --url 'https://api.github.com/repos/AmanoTeam/Atar/releases/latest')")"
+            # declare -r ATAR_TARBALL='/tmp/toolchain.tar.xz'
+            # declare -r ATAR_URL="https://github.com/AmanoTeam/Atar/releases/download/${ATAR_TAG}/x86_64-unknown-linux-gnu.tar.xz"
+            
+            # curl --silent --connect-timeout '10' --retry '15' --retry-all-errors --fail --location --url "${ATAR_URL}" --output "${ATAR_TARBALL}"
+            # tar --directory="$(dirname "${ATAR_TARBALL}")" --extract --file="${ATAR_TARBALL}"
+            
+            # export ATAR_HOME='/tmp/atar'
+            export PATH="${ATAR_HOME}/bin:${PATH}"
+            
+            source "${ATAR_HOME}/usr/local/share/atar/autotools/${{ matrix.target }}.sh"
+        elif [[ '${{ matrix.target }}' == *'-android'* ]]; then
+            declare -r PINO_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --url 'https://api.github.com/repos/AmanoTeam/Pino/releases/latest')")"
+            declare -r PINO_TARBALL='/tmp/toolchain.tar.xz'
+            declare -r PINO_URL="https://github.com/AmanoTeam/Pino/releases/download/${PINO_TAG}/x86_64-unknown-linux-gnu.tar.xz"
+            
+            curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --location --url "${PINO_URL}" --output "${PINO_TARBALL}"
+            tar --directory="$(dirname "${PINO_TARBALL}")" --extract --file="${PINO_TARBALL}"
+            
+            export PINO_HOME='/tmp/pino'
+            export PATH="${PINO_HOME}/bin:${PATH}"
+            
+            source "${PINO_HOME}/usr/local/share/pino/autotools/${{ matrix.target }}.sh"
+        fi
         
         bash './build.sh' '${{ matrix.target }}'
+    - name: Setup upterm session
+      uses: lhotari/action-upterm@v1
+    - name: Create logs
+      if: always()
+      run: |
+        declare logs=''
+        
+        while read file; do
+            logs+="${file} "
+        done <<< $(find "/tmp/"*"/build" -wholename '*.log' -o -wholename '*.yaml')
+        
+        tar --create --file=- ${logs} | xz --threads='0' --compress -9 > '/tmp/logs.tar.xz'
+    - name: Upload logs
+      if:  always()
+      uses: actions/upload-artifact@main
+      with:
+        name: ${{ matrix.target }}-logs
+        if-no-files-found: error
+        path: |
+            /tmp/logs.tar.xz
     - name: Generate tarball
       run: |
         declare tarball_filename='/tmp/${{ matrix.target }}.tar.xz'
